In [ ]:
'1.Write a Python program to print "Hello,World"'
print("Hello, World!")

Hello, World!

In [ ]:
'2.Write a Python program that displays your name and age?'
name = input(print("Enter your name: "))
age = input(print("Enter your age: "))
print(f"My name is: {name}", f"and age is {age}")

Enter your name:
NoneChethan
Enter your age:
None30
My name is: Chethan and age is 30

In [ ]:
import keyword
'3.Write w code to print all the pre-defined keywords in Python using keywords library.'
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [ ]:
import keyword
'4.Write a code to check given word is python keyword'
word = input(print("Enter a word: "))
if(keyword.iskeyword(word)):
  print("Entered word is a python keyword")
else:
  print("Entered word is not a python keyword")

Enter a word:
Nonefor
Entered word is a python keyword

In [ ]:
'5. Create a list and tuple in Python, and demonstrate how attempting to change an elements works differently for each'

solar_system = ["sun","venus","mercury","earth","mars","jupiter","saturn"]
planets = ("venus","mercury","earth","mars","jupiter","saturn","neptune")
print(solar_system)
print(planets)
solar_system.append("neptune")
solar_system[4] = "moon"
#planets.append("sun","moon")
planets[0] = "sun"
print(solar_system)
print(planets)

['sun', 'venus', 'mercury', 'earth', 'mars', 'jupiter', 'saturn']
('venus', 'mercury', 'earth', 'mars', 'jupiter', 'saturn', 'neptune')

TypeError: 'tuple' object does not support item assignment

In [1]:
'6.Write a function to demonstrate the behaviour of mutable and immutable arguments'
def demonstrate_mutable_immutable(a, b):
    print("Before modification:")
    print("Immutable (int) a =", a)
    print("Mutable (list) b =", b)

    # Try to modify both
    a += 10         # Creates a new integer object (immutable)
    b.append(100)   # Modifies the same list object (mutable)

    print("\nAfter modification inside function:")
    print("Immutable (int) a =", a)
    print("Mutable (list) b =", b)

# Call the function
x = 5            # Immutable
y = [1, 2, 3]     # Mutable
demonstrate_mutable_immutable(x, y)

print("\nAfter function call:")
print("x =", x)      # Unchanged
print("y =", y)      # Changed

Before modification:
Immutable (int) a = 5
Mutable (list) b = [1, 2, 3]

After modification inside function:
Immutable (int) a = 15
Mutable (list) b = [1, 2, 3, 100]

After function call:
x = 5
y = [1, 2, 3, 100]

In [ ]:
'7. Write a program to perform basic arithmatic operation on two user inputs'
num1 = int(input(print("Enter a first number: ")))
num2 = int(input(print("Enter a second number: ")))
print(f"Addition of {num1} and {num2} is: {num1 +num2}")
print(f"Subtraction of {num1} and {num2} is: {num1 - num2}")
print(f"Multiplication of {num1} and {num2} is: {num1 * num2}")
print(f"Devision of {num1} and {num2} is: {num1/num2}")
print(f"Modulus of {num1} and {num2} is: {num1 % num2}")

Enter a first number:
None20
Enter a second number:
None10
Addition of 20 and 10 is: 30
Subtraction of 20 and 10 is: 10
Multiplication of 20 and 10 is: 200
Devision of 20 and 10 is: 2.0
Modulus of 20 and 10 is: 0

In [ ]:
'8.Write a program to demonstrate the use of logical operators'
var1 = int(input(print("Enter a number")))
var2 = int(input(print("Enter a another number")))
print(f"{var1%2 == 0 and var2%2 == 0}")
print(f"{var1%2 == 0 or var2%2 == 0}")
print(f"{not(var1>var2)}")

Enter a number
None20
Enter a another number
None1
False
True
False

In [ ]:
'9. Write a programme to convert user input from string to integer, float and boolean types'
user_input = input(print("Enter a number: "))
'9. Write a programme to convert user input from string to integer, float and boolean types'
print(f"String to Integer {int(user_input)}")
print(f"String to float: {float(user_input)}")
print(f"String to boolean: {bool(user_input)}")

Enter a number:
None10
String to Integer 10
String to float: 10.0
String to boolean: True

In [ ]:
'10. Write a code to demonstrate type casting with list elements'
elements = ["fruits", ("tuple"), 4, True, ["list"],None,]
print(elements[1])
for i in elements:
  print(f"Type of {i} is: {type(i)}")

tuple
Type of fruits is: <class 'str'>
Type of tuple is: <class 'str'>
Type of 4 is: <class 'int'>
Type of True is: <class 'bool'>
Type of ['list'] is: <class 'list'>
Type of None is: <class 'NoneType'>

In [ ]:
'11.Write a program that checks a number is positive,negetive or zero'
num_list = [3,1,0,-3,0,-10,-2,0,19]
for i in num_list:
  if(i > 0):
    print(f"{i} is a positive number")
  elif(i < 0):
    print(f"{i} is a negetive number")
  else:
    print(f"{i} is zero")

3 is a positive number
1 is a positive number
0 is zero
-3 is a negetive number
0 is zero
-10 is a negetive number
-2 is a negetive number
0 is zero
19 is a positive number

In [ ]:
'12.Write a forloop to print a numbers from 1 to 10 '
for number in range(1,11):
  print(number, end=" ")

1 2 3 4 5 6 7 8 9 10

In [ ]:
'13.Write a python program that finds sum of all even numbers between 1 to 50'
num = 0
sum = 0
while (num <= 50):
  sum = num + sum
  num+=2
print(sum)

650

In [ ]:
'14. Write a program to reverse a string using while loop'
word = input(print("Enter a word/sentence"))
for char in range(len(word)-1,-1,-1):
  print(word[char],end="")

Enter a word/sentence
NoneLove
evoL

In [ ]:
'15.Wrote a program to calculate the factorial of a number provided by user using a while loop'
num = int(input(print("Enter a number")))
factorial = 1
while(num > 0):
   factorial = num*factorial
   num-=1
print(factorial)

Enter a number
None5
120